name: PHP Extension Validation

on:
    pull_request:
        branches: [main]
        types: [opened, synchronize, reopened]

jobs:
    test-php:
        runs-on: windows-latest
        strategy:
            matrix:
                os: [win10-amd, win10-intel, win11-amd, win11-intel]

        steps:
            - name: Checkout PR branch
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Get diff of releases.properties
              run: |
                  git fetch origin main
                  git diff origin/main...HEAD -- releases.properties | `
                    Select-String '^+' | `
                    Where-Object { $_ -notmatch '^\+\+' } | `
                    ForEach-Object { $_.Line.TrimStart('+') } > new_versions.txt

            - name: Loop through new PHP versions
              run: |
                  $versions = Get-Content new_versions.txt
                  foreach ($version in $versions) {
                    Write-Host "Testing PHP $version on ${{ matrix.os }}"
                    # Insert your extension validation logic here
                  }

            - name: Generate badge
              if: success()
              run: |
                  echo "![PHP Test Passed](https://img.shields.io/badge/PHP%20Test-${{ matrix.os }}-green)" >> badge.md

            - name: Comment on PR (success)
              if: success()
              run: |
                  gh pr comment ${{ github.event.pull_request.number }} --body "✅ PHP extension test passed on `${{ matrix.os }}`. See badge below:\n\n$(cat badge.md)"

            - name: Comment on PR (failure)
              if: failure()
              run: |
                  gh pr comment ${{ github.event.pull_request.number }} --body "❌ PHP extension test failed on `${{ matrix.os }}`. Please check logs."

            - name: Send email alert on failure
              if: failure()
              uses: dawidd6/action-send-mail@v3
              with:
                  server_address: ${{ secrets.SMTP_SERVER }}
                  server_port: ${{ secrets.SMTP_PORT }}
                  username: ${{ secrets.SMTP_USER }}
                  password: ${{ secrets.SMTP_PASS }}
                  subject: "PHP Extension Test Failed on ${{ matrix.os }}"
                  to: "admin@bearsampp.com"
                  from: "admin@bearsampp.com"
                  body: |
                      The PHP extension test failed for `${{ matrix.os }}`.
                      Please review the logs in the GitHub Action run:
                      https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
